### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [mikolalysenko/ama#1]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by mikolalysenko** [comment]
A mess!
![photo on 7-11-15 at 1 23 pm 2](https://cloud.githubusercontent.com/assets/231686/8633793/ae905b9c-27a1-11e5-9e04-653df49b48d2.jpg)

**Comment by AchoArnold** [comment]
wow how do you guys get 7k unread emails?
