### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [mikolalysenko/ama#14]

**Comment by mikolalysenko** [comment]
I've taught a few courses.  Here are some videos:

https://www.youtube.com/playlist?list=PLESnaHRvLM-72xIXf8dL2EOqN8UgAZMj7

**Comment by mikolalysenko** [comment]
Oh and then there are the shader-school and webgl-workshops that @hughsk and @chrisdickinson helped out with.
