### ISSUE TITLE
What's your biggest annoyance with Node.js?

### ISSUE THREAD

**Issue by sindresorhus** [mikolalysenko/ama#2]

**Comment by mikolalysenko** [comment]
Generally anything having to do with Windows, like paths or binary objects.

Also, I really wish there was a way to publish compiled native binaries on npm and have them work reliably across Linux/OSX/Windows/etc.  I've looked at doing this a couple of times using emscripten, but those tools move so fast and erratically that any patches I start working on become obsolete before I can get them done.  Maybe once WebAssembly becomes a thing it would be worth revisiting this.

**Comment by sindresorhus** [comment]
:+1: Hah. This is exactly what I would have answered.
