### ISSUE TITLE
How did you get into making node modules?

### ISSUE THREAD

**Issue by sindresorhus** [mikolalysenko/ama#5]

**Comment by mikolalysenko** [comment]
It is all @maxogden's fault.

**Comment by sindresorhus** [comment]
Elaborate? ;)

**Comment by mikolalysenko** [comment]
I wrote some JS code a while back for my blog to do voxel stuff (this was back in the early days of Minecraft before Notch was a billionaire).  
- http://0fps.net/2012/06/30/meshing-in-a-minecraft-game/
- http://0fps.net/2012/01/14/an-analysis-of-minecraft-like-engines/

@maxogden and @substack used some of those algorithms to start voxel.js, and also generously took their time to help explain how node/npm worked.  I had used browserify previously in some [side projects](https://github.com/mikolalysenko/MineHack)/[random experiments](https://github.com/mikolalysenko/NodeMinecraftThing) back in the early pre-THREEjs days of WebGL to try doing voxel things, but by interacting with voxel.js I became much more involved in writing modules.

Once I got some basic ideas through these interactions, I kind of branched off and did my own thing working on stuff like [ndarray](https://github.com/scijs/ndarray) and [stack.gl](http://stack.gl), and lots of other random experiments along the way.
