### ISSUE TITLE
What's the favorite module you've made and why?

### ISSUE THREAD

**Issue by sindresorhus** [mikolalysenko/ama#6]

**Comment by mikolalysenko** [comment]
Hard to pick a favorite, but there are a few I am especially fond of:

One that I really like is [box-intersect](https://github.com/mikolalysenko/box-intersect), which solves an important problem in a unique, general and efficient way.  It is also pretty fast, and has the nice property that you can use it in whatever dimension you like.  Some things you can do with it are [Boolean operations](https://github.com/mikolalysenko/overlay-pslg), or collision detection for video games/physics simulations.

Another one which is pretty fundamental is this [n-dimensional convex hull](https://github.com/mikolalysenko/convex-hull) module I wrote a while back.  The output from that algorithm is exact in the sense that it never makes rounding errors or misclassifies points on the hull.  Using that gadget, you can build n-dimensional [Delaunay triangulations](https://github.com/mikolalysenko/delaunay-triangulate) and [Voronoi diagrams](https://github.com/mikolalysenko/voronoi-diagram) as well, and their variants like [weighted Delaunay triangulations](https://github.com/mikolalysenko/weighted-delaunay) or power diagrams.  In 2D, you can combine those with a [fast point location data structure](https://github.com/mikolalysenko/point-in-region) and get logarithmic time complexity nearest neighbor searches, which is a hell of a lot faster than anything else out there on npm for doing proximity queries.  Finally, you can also use it to do fun constructions like vertex enumeration (which is just the dual of convex hull's) or construct [Minkowski sums of convex polytopes](https://github.com/mikolalysenko/convex-minkowski-sum), [alpha-shapes](https://github.com/mikolalysenko/alpha-shape), etc.  Overall, it is a very useful algorithmic primitive!

There are also a few other ones which I really like:
- [surface-nets](https://github.com/mikolalysenko/surface-nets): n-dimensional surface extraction (think Marching cubes/squares/dual contouring, only faster and works in any dimension)
- [dynamic-forest](https://github.com/mikolalysenko/dynamic-forest): This was lots of fun to write, though less clear if it is actually that useful. It is basically a dynamic graph data structure where you can add and remove edges in amortized polylog time and answer connectivity queries in O(1).
- [pitch-shift](https://github.com/mikolalysenko/pitch-shift) Applies a pitch shift to an audio signal (basically a local time domain rescaling) while preserving the higher level structure of a sound.  You can probably use this to build an auto-tune app
- [detect-pitch](https://github.com/mikolalysenko/detect-pitch) A realtime-ish pitch detection module.  It could be a bit better, but works surprisingly ok for how simple it is
- [binary-search-bounds](https://github.com/mikolalysenko/binary-search-bounds) Literally the only binary search on npm for getting predecessor/successor queries (which is the only reason to use a binary search in the first place!)

**Comment by arthurvr** [comment]
Cool! :+1:
